[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

; Point directly to your custom partition file
board_build.partitions = partitions.csv

lib_deps = 
    h2zero/NimBLE-Arduino@^1.4.3
    d03n3rfr1tz3/HC-SR04@^1.1.3
    madhephaestus/ESP32Servo@^3.2.1
    bblanchon/ArduinoJson@^7.0.0
    knolleary/pubsubclient@^2.8
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git